apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  labels: 
    {{- include "helm-charts.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
      matchLabels:
        {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name}}
    spec:
      containers:
        - name: {{ .Values.service.name}}
          image: {{ .Values.image.repository}}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.service.targetPort}}